# site settings
title: Hi my name is Arturo, welcome to my website!
subtitle: Here you will find some information about myself
email: arturogalofreestape@gmail.com
description: Please contact me if you have any further questions
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://arturogalofre.github.io # the base hostname & protocol for your site
author: Arturo Galofre
street_address: Boston
city: Boston
state: Ma
zip_code: 021309
country: United States of America
phone: (773) 543-4884

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/arturogalofre
  GitLab:
  Google-Plus: # https://plus.google.com/u/
  Instagram:
  LinkedIn: https://www.linkedin.com/in/arturo-galofre-estape
  Twitter: # https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
